apiVersion: v1
kind: Pod
metadata:
  name: good
spec:
  containers:
    - name: app
      image: orders:1.0
---
apiVersion: v1
kind: Pod
metadata:
  name: bad
spec:
  containers:
    - name: app
      image: orders:latest
